# Site
name: "Zero Knowledge Proofs in the Real World"
title: "Zero Knowledge Proofs in the Real World"
description: "A collection of real-world implementations of ZKPs, alongside promising and informative work from industry and academia."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  nojan:
    name: Nojan Sheybani
    display_name: Nojan Sheybani
    avatar: assets/images/nojan.png
    email: nsheyban@ucsd.edu
    web: https://nojansheybani.github.io
    twitter: https://x.com/nojansheybani
    description: "Developer of this website. 4th-year PhD student at UC San Diego advised by Professor Farinaz Koushanfar focusing on hardware/software co-design of privacy-preserving systems."

  amir:
    name: AmirHossein Adibfar
    display_name: AmirHossein Adibfar
    avatar: assets/images/amir.png
    email: aadibfar@ucsd.edu
    description: "2nd-year PhD student at UC San Diego advised by Professor Farinaz Koushanfar."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
